apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaos-lab-api
  namespace: chaos-lab
spec:
  ingressClassName: nginx
  rules:
    - host: chaos-lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chaos-lab-api
                port:
                  number: 80
