apiVersion: v1
kind: Secret
metadata:
  name: chaos-lab-secrets
  namespace: chaos-lab
type: Opaque
stringData:
  db-url: "postgresql://chaos:chaos@postgres:5432/chaoslab"
  mongodb-url: "mongodb://chaos:chaos@mongo:27017/chaoslab?authSource=admin"
  jwt-secret: "segredo123"
  hmac-secret: "curto"
