apiVersion: v1
kind: Secret
metadata:
  name: chaos-lab-secrets
  namespace: chaos-lab
type: Opaque
stringData:
  postgres-url: "postgresql://chaos:chaos@localhost:5432/laboratoriodocaos"
  mongodb-url: "mongodb://chaos:chaos@localhost:27017/chaoslab?authSource=chaoslab"
  jwt-secret: "98226489150527ef0753d0b3cb8763cd8100c1d4dde04858ef5827de79482576"
  hmac-secret: "hmac-local-chaos-lab"
